server:
  port: ${PORT:8081}

spring:
  application:
    name: player-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/player_db}
    username: ${SPRING_DATASOURCE_USERNAME:tbe_user}
    password: ${SPRING_DATASOURCE_PASSWORD:tbe_pass}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: ${JPA_SHOW_SQL:true}
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

steam:
  api:
    key: ${STEAM_API_KEY:}
    base-url: https://api.steampowered.com

jwt:
  secret: ${JWT_SECRET:supersecretkey_changeinproduction_minimum256bits!!}
  expiration-ms: 86400000

springdoc:
  api-docs:
    enabled: ${SPRINGDOC_API_DOCS_ENABLED:true}
  swagger-ui:
    path: /swagger-ui.html
    enabled: ${SPRINGDOC_SWAGGER_UI_ENABLED:true}